### ISSUE TITLE
near deploy needs updating in blank_project

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/near-shell#104]
<img width="1238" alt="Screenshot 2019-08-05 13 02 17" src="https://user-images.githubusercontent.com/6679554/62563162-47deb300-b837-11e9-9e3b-48aa83666223.png">

edit: Updated image to highlight the deprecated warning not the error due to account

**Comment by janedegtiareva** [comment]
I can't reproduce this anymore.  Could you confirm if this is still happening?

**Comment by potatodepaulo** [comment]
Thanks for checking this was fixed a while ago.
