### ISSUE TITLE
Failed to Deserialize the Genesis Config

### ISSUE THREAD

**Issue by joesixpack** [nearprotocol/near-shell#108]
![nearprotocol 1](https://user-images.githubusercontent.com/23145642/62660943-6078c700-b924-11e9-8f24-a9dea72fecf1.png)

**Comment by bowenwang1996** [comment]
What's the command you run to start the node? It looks like you may have some old genesis file.

**Comment by joesixpack** [comment]
sudo ./scripts/start_testnet.py --local

I deleted the data dir.  What is safe to delete here:

![image](https://user-images.githubusercontent.com/23145642/62662650-9cfaf180-b929-11e9-8f42-f5c6c2c0c43b.png)

**Comment by bowenwang1996** [comment]
Since you are probably using the old version, you might want to delete the whole folder altogether. What matters here is `genesis.json`.

**Comment by joesixpack** [comment]
Thanks, its working now!

I'm running with --local because the Docker instructions are now missing.
