### ISSUE TITLE
Returning u64 prevents compilation

### ISSUE THREAD

**Issue by DanielRX** [nearprotocol/near-shell#110]
```main.ts
export function broken_function(): u64[] {
    return [1, 2];
}
```
Trying to compile this results in the following error: 
```
ERROR TS2339: Property 'toString' does not exist on type 'u64'.
    encoder.setString(null, value[i].toString());
    in ../out/main.near.ts(42,33)
```

**Comment by bowenwang1996** [comment]
This unfortunately is a known issue in assemblyscript. There is a PR tracking it https://github.com/AssemblyScript/assemblyscript/pull/726

**Comment by willemneal** [comment]
@DanielRX The encoding code has been updated since and this should work.

**Comment by willemneal** [comment]
Here's a staging near studio with it as an example: https://near-studio-staging-pr-151.onrender.com/?f=6vx6mkjgt

**Comment by MaxGraey** [comment]
This issue could be solved with latest version of AS. Did you try it already?

**Comment by janedegtiareva** [comment]
This is fixed.
