### ISSUE TITLE
Money in the shell should be denominated in "Near"

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#113]
Currently they are denominates in attoNEAR, which means that staking 10 NEARs is large number with 19 zeros which is hard to keep track.
All the `amounts`, including provided by user and printed out should display amount in NEAR (and use mantissa like 0.001 Ⓝ if it's smaller than one)

**Comment by janedegtiareva** [comment]
Do we want to fix this on nearlib level so that all clients don't have to reimplement?

**Comment by vgrichina** [comment]
@icerove PR in progress https://github.com/nearprotocol/near-shell/pull/149

**Comment by icerove** [comment]
did this already already fix in PR or still need fixing?

**Comment by janedegtiareva** [comment]
this is done
