### ISSUE TITLE
Generate templates found in studio using CLI tool

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/near-shell#14]
It would be cool to be able to reproduce any of the templates that are in Studio from the command line.

```
near new $TEMPLATE_NAME $PROJECT_NAME --project_dir $DIR
```

**Comment by vgrichina** [comment]
I think we should just use some existing scaffolding system, e.g. https://yeoman.io or http://slushjs.github.io instead of re-implementing it here.

This applies to existing `new-project` command as well.

**Comment by janedegtiareva** [comment]
I looked at yeoman, and I personally don't like it. It has a lot of weird/obscure conventions and is overly complex for what we need right now.

**Comment by evgenykuzyakov** [comment]
I also think we don't need templates. People can just clone templates from github repo

**Comment by potatodepaulo** [comment]
I'm heavily influenced by the leiningen template system, which allows (and encourages) users to build their own templates. https://github.com/technomancy/leiningen/blob/master/doc/TEMPLATES.md

**Comment by potatodepaulo** [comment]
They accomplish this with Maven, but there's no reason we couldn't do the same with npm packages.
![Screenshot 2019-03-26 16 29 30](https://user-images.githubusercontent.com/6679554/55040108-4fb65d00-4fe4-11e9-84da-551b6488b2c8.png)

**Comment by vgrichina** [comment]
@potatodepaulo 
> but there's no reason we couldn't do the same with npm packages.

that's exactly what tools I linked above are doing.

> I looked at yeoman, and I personally don't like it. It has a lot of weird/obscure conventions and is overly complex for what we need right now.

Prob simplest way would be then to plug into `npm init` / `yarn create` similar to https://github.com/facebook/create-react-app#creating-an-app

I am not biggest fan of `yo`, however note that it's benefit is that you can have commands runnable after project init to do stuff like create new contract, create new model, etc.

**Comment by vgrichina** [comment]
@janedegtiareva @potatodepaulo I'm going to prototype `npm init` solution unless there are any objections, cause I want to make stuff deployable on GH pages and this means there is need to plumb contract name in `config.js` or smth like that.

**Comment by janedegtiareva** [comment]
If you do, could you check the existing stuff that's used from main.html? (It's a crufty "Todo: fill this value by hand that I wanted to revisit)

**Comment by vgrichina** [comment]
@janedegtiareva that was the plan
