### ISSUE TITLE
Expected behavior of NEAR CLI tool from new user

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/near-shell#15]
Here are some things I tried when I first used the tool installing globally from npm.

These are based on experiences with other CLI tools that generate apps.
E.g. 
- [Angular](https://cli.angular.io/)
- [Leiningen](https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md)
- [Create React App](https://github.com/facebook/create-react-app)

## generating a project
```
near new .
# generates a new generic hello world in the current dir

near new my-project ---project_dir=~/directory
# generates project in new dir ~/directory/my-project 

near new $TEMPLATE $PROJECT
# generates a project in current dir from one of the studio templates (https://github.com/nearprotocol/near-shell/issues/14)
```
## getting help
```
near --help
near -h
# returns help for all commands

near $CMD -h
# returns help for specific command
```

## making an error in the commands
```
near ne
# tells me what commands I have at my disposal
```

**Comment by vgrichina** [comment]
I think generally we also want to avoid re-implementing tool to generate project from templates, cause there are few existing ones:

https://github.com/nearprotocol/near-shell/issues/14#issuecomment-476815067

**Comment by janedegtiareva** [comment]
0.0.14 should address a lot of these except for diff templates.
