### ISSUE TITLE
homeDir option seems not working

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/near-shell#159]
After giving --homeDir, it still tries to find validator_key.json in ~/.near
```
➜  nearcore git:(staging) ✗ ls ~/.near/node0/ config.json
data  genesis.json  node_key.json  signer_key.json  validator_key.json 
➜  nearcore git:(staging) ✗ NODE_ENV=local near --homeDir ~/.near/node0 send aaaaa bbbbb 3
[WARNING] Didn't find config at /home/bo/workspace/nearcore/src/config, using default shell config
Sending 3 NEAR to bbbbb from aaaa
Failed to load master account key from /home/bo/.near/validator_key.json: Error: ENOENT: no such file or directory, open '/home/bo/.near/validator_key.json'
```

**Comment by janedegtiareva** [comment]
Which version of near-shell was this on?

**Comment by janedegtiareva** [comment]
Looks like this is happening on latest, I will take a look

**Comment by k06a** [comment]
Still happening for 0.18.0 version

**Comment by k06a** [comment]
Version 0.18.0:
- Master key is loaded successfully
- Trying to find config in wrong directory:
  ```
  [WARNING] Didn't find config at /Users/k06a/Projects/bridge/ethrelay/src/config, using default shell config
  ```

**Comment by mikedotexe** [comment]
we've taken the `--homeDir` option out recently. A new direction for `near-shell` will take place after the NEP comes out from Damon, so this issue is a bit stale at this point. Closing this; thanks everyone for reporting.
