### ISSUE TITLE
Missing public key for -ID- in default

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-shell#161]
On log-in I get the following return message
“Please enter the accountId that you logged in with: -myID-
Missing public key for -myID- in default
Logged in with -myID-”

What is the expected behaviour? Is the user supposed to add the public key; if yes, how? Is this message needed?

**Comment by hoekevin** [comment]
that's not an error.Missing public key for -myID- in default means this AccoutId have no public key in nearshell,and nearshell will then create one publickey for it and stored it in Current_directory/neardev/defalut/YourAccountId.json

**Comment by hoekevin** [comment]
You can even copy your wallet key pair to this folder and stored it in the same format to manage your wallet.

**Comment by AnaisUrlichs** [comment]
The problem is that we received this question several times; thus, have to re-explain it. Could we change the error message into e.g.
- No public key registered to this ID
Or something that sounds less like it requires immediate action by the user?

**Comment by icerove** [comment]
now when logged in successfully, it will show `Logged in as {accountId} with public key {public-key (ed25519:CV16URecQ1jshXQxzBRZStywfFBCuAVFyFYk39ngohuh)} successfully`
