### ISSUE TITLE
Can not sign transactions

### ISSUE THREAD

**Issue by AlexDCryptoC** [nearprotocol/near-shell#173]
![near transaction](https://user-images.githubusercontent.com/18679675/67870970-525bd080-fb38-11e9-9c1a-c0e9ee58d9a6.JPG)

Even i can not send tokens from a wallet to another wallet

**Comment by bowenwang1996** [comment]
I think it is because you did not initiate the command from the directory where you ran `near login`. To double check, do you have a `neardev` folder inside `nearocre`?

**Comment by bowenwang1996** [comment]
So you should run the command from where you have that folder.
