### ISSUE TITLE
Generate account keys

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/near-shell#177]
For stake wars validators need to generate keypairs for their accounts and right now there is not a good way to do this (we have a hacky solution that involves passing a flag to the script that starts the node but it is suboptimal). It would be nice to have:
* Command for account key generation. The command should support generating multiple keypairs for the same account.
* It seems to me that near-shell only supports one key per account. If that is the case, we should improve it to support multiple keys per account.

**Comment by vgrichina** [comment]
> It seems to me that near-shell only supports one key per account. If that is the case, we should improve it to support multiple keys per account.

why do we need to keep multiple keys per account on a single device?

**Comment by bowenwang1996** [comment]
Good point. I guess there is no need :)
