### ISSUE TITLE
cli.js not found when installing locally

### ISSUE THREAD

**Issue by ColinEberhardt** [nearprotocol/near-shell#179]
With reference to this commit: https://github.com/nearprotocol/near-shell/commit/84c126831f34301ae51e833dcf854efb50540917 the shell command has been split into `cli.js` and `near`.

However, when installing this package, only the `near` file is copied into `node_modules/.bin`:

https://github.com/nearprotocol/near-shell/blob/master/package.json#L22

As a result, the `cli.js` file is not found when executing near shell commands.

**Comment by vgrichina** [comment]
I believe this is fixed now https://github.com/nearprotocol/near-shell/commit/5aded68991682d30426e1d3cd7f3a05e6fb05c2c, feel free to re-open if not.
