### ISSUE TITLE
Invalid subcommand doesn't show any errors

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#259]
Currently running non-existent / invalid sub-command doesn't result in any error.
```
near transfer acc1 my_validator 1
[WARNING] Didn't find config at /Users/cypress/projects/nearprotocol/stakewars/staking-contract/src/config, using default shell config
{ networkId: 'local',
  nodeUrl: 'http://localhost:3030',
  keyPath: '/Users/cypress/.near/validator_key.json',
  walletUrl: 'http://localhost:4000/wallet',
  contractName: 'near-hello-devnet' }
(node:53295) ExperimentalWarning: The fs.promises API is experimental
```

**Comment by vgrichina** [comment]
@mikedotexe related PR https://github.com/nearprotocol/near-shell/pull/51

Note that just re-enabling strict mode is problematic, as then loading config fails when command doesn't support all of the options in config.

It should be possible to solve by loading and merging config with options manually vs going through yargs. Best place to put it is likely yargs middleware:
https://github.com/yargs/yargs/blob/master/docs/advanced.md#middleware

**Comment by mikedotexe** [comment]
> @mikedotexe related PR #51
> 
> Note that just re-enabling strict mode is problematic, as then loading config fails when command doesn't support all of the options in config.
> 
> It should be possible to solve by loading and merging config with options manually vs going through yargs. Best place to put it is likely yargs middleware:
> https://github.com/yargs/yargs/blob/master/docs/advanced.md#middleware

Super helpful context, thank you. I took another approach here
https://github.com/nearprotocol/near-shell/pull/262
that doesn't use the strict mode, but has a default.
Knowing the history of this issue, I'll tag Jane and you on it since you'll immediately understand

**Comment by mikedotexe** [comment]
Finally got this through, thanks for the patience, Illia.
