### ISSUE TITLE
New flow for login hangs when web flow is ran on different machine

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#297]
Steps to reproduce:

1. Running `near login` on the server or inside the VM
2. Copy the URL and run it on your machine.
3. Approve the adding key in your NEAR Wallet web page.
4. Switch back to the server / VM.
5. Observe that `near login` still hands without making any progress and giving any alternative option to finalize the step.

# Alternative solution

If we add lookup of accounts by public key into explorer backend, we can actually use that to lookup which account authorized this key without needing to open port.

CC @kcole16 @frol

**Comment by mikedotexe** [comment]
@ilblackdragon making sure I understand the steps to reproduce. Is this specific to running "on the server"?
Here's what I tried:
```
near login --networkId betanet --nodeUrl "https://rpc.betanet.nearprotocol.com" --walletUrl "https://wallet.betanet.nearprotocol.com" --helperUrl "https://helper.beatnet.nearprotocol.com"
Using options: {
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.nearprotocol.com',
  walletUrl: 'https://wallet.betanet.nearprotocol.com',
  helperUrl: 'https://helper.beatnet.nearprotocol.com',
  contractName: undefined
}

Please authorize NEAR Shell on at least one of your accounts.

If your browser doesn't automatically open, please visit this URL
https://wallet.betanet.nearprotocol.com/login/?title=NEAR+Shell&public_key=ed25519%3AAo6E9ZN62ETjk6o3ikqZa9eLo16ALkzz7q9mH7QYa6Bn
Logged in as [ mikedotexe ] with public key [ ed25519:Ao6E9Z... ] successfully
```
It created the key as expected

**Comment by ilblackdragon** [comment]
Ok, steps to reproduce:  open link on a different machine you running this.
Talked to Peter about possible solution @potatodepaulo

**Comment by potatodepaulo** [comment]
@ilblackdragon and I discussed how this can work:
- [ ] Dev account for dev-user created by test.
- [ ] 	Dev-user account creates contract. (This account stays logged in as per https://github.com/near/devx/issues/116. Don’t ever overwrite keys)
- [ ] 	Ask in command line for confirmation of env before launching auto-login

**Comment by ilblackdragon** [comment]
@potatodepaulo First two items are not related to this issue. Also want to note that we have an (approved?) NEP for improving shell. Added comments there about first two items - https://github.com/nearprotocol/NEPs/pull/31#issuecomment-606615736

Last item is indeed the thing for this issue - figure out a way to confirm with user that they are planning to open NEAR Wallet on the same machine and `near login` command is been ran. 
Options when it's not true:
 - VM
 - SSH to server

Also, I want to note that some computers have ports not openable without special permissions, including MS Windows has firewalls that prevent opening ports by non authorized software. Was this case tested?

**Comment by janedegtiareva** [comment]
Maybe we can bring back the option to manually type in your account id in shell at the end of login as a fallback? That was the original reason why the manual step was implemented in the first place.

**Comment by potatodepaulo** [comment]
@janedegtiareva I like the fallback idea. We should do both. Basically a yes/no questions from the user before nice UX flow runs. Then if the user wasn't paying attention and answered randomly, the fallback runs (maybe after a timeout).

**Comment by frol** [comment]
@ilblackdragon Tracking the access key via some lookup with a "third-party" centralized service does not feel right to me. So I like the proposed fallback solution after some timeout asking to enter an account ID

**Comment by mikedotexe** [comment]
I won't steer us too far off topic but want to say this is the perfect example of a project-based setting that I envision will live in something like `/project/directory/.near/shell-info.js` (or `shell-info.env`) that stores the most recent version of `near-shell` used in this project as well as the answer to the question.
```
{
  lastShellVersionUsed: "0.19.0",
  promptAfterLogin: true
}
```
These project-specific settings will allow us to upgrade a project as `near-shell` matures and changes fundamental features like key storage and location.
This is **different** than configuration like `nodeUrl` and whatnot. We need both config and settings longterm.
Look forward to jumping on this soon.

**Comment by vgrichina** [comment]
@mikedotexe @janedegtiareva @frol fallback is already there, I assume just is not triggered properly:
https://github.com/nearprotocol/near-shell/blob/dbb808479c98bd072b63e1f405548a552a77a0a6/index.js#L101
