### ISSUE TITLE
Regression: new project is broken

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-shell#30]
At least one dev flow is broken. 
run after new_project, npm install, npm run-script test - this should run tests in a sandbox environment (i.e. separate instance of contract deployed and used). local_test_environment is supposed to be used for that, and it's being ignored right now.

**Comment by vgrichina** [comment]
Fixed in https://github.com/nearprotocol/near-shell/commit/e6c0716569faeaea381e8fe96e2c4e678e5c0150

CI in https://github.com/nearprotocol/near-shell/commit/1485eb4ef95e43fd469827371af947d93e2512e5
