### ISSUE TITLE
New_project requires out dir

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/near-shell#36]
If we create a project using `near new_project .` and then run `npm i && near build` it would give the following error `Error: ENOENT: no such file or directory, open 'out/model.near.ts'` and can be resolved by manually creating the out directory.

**Comment by vgrichina** [comment]
Just do `npm run build`, it should work fine

**Comment by bowenwang1996** [comment]
Looks like I have outdated near shell.

**Comment by bowenwang1996** [comment]
It works now. Might have been a bug with npm.

**Comment by vgrichina** [comment]
@bowenwang1996 `near build` still shouldn't work, directory is created by npm script
