### ISSUE TITLE
`near create_account` should be able to take account name without `--accountId`

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-shell#46]

**Comment by potatodepaulo** [comment]
This should be true for new_project as well.

**Comment by vgrichina** [comment]
@potatodepaulo if you are interested to do a pass on CLI UX, it's relatively easy to tweak it, see e.g. how function call command is defined here:
https://github.com/nearprotocol/near-shell/blob/master/bin/near#L31
