### ISSUE TITLE
Deploying generic wasm contracts from near-shell

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-shell#48]
Near shell cannot be used for users working with Rust contracts:
* It requires `config.js`;
* It requires contract helper. near shell is supposed to supersede pynear, by pynear was able to work without locally running contract helper.

To reproduce:
* Start local node, without contract helper, e.g. using `./run_local_dev.sh` from `near-ops`;
* Execute the following commands (you can find the wasm contract here https://www.dropbox.com/s/l8vjk0p6aef52as/test_contract_bg.wasm?dl=0): 

```
near create_account --useDevAccount --account_id "francis"          ✔  10014  10:01:20
[WARNING] Didn't find config at /Users/zaver/Projects/near-shell/src/config
```

```
near deploy --useDevAccount --account_id "francis" --wasmFile /Users/zaver/Projects/nearcore/runtime/rust-api/test-contract/pkg/test_contract_bg.wasm
[WARNING] Didn't find config at /Users/zaver/Projects/near-shell/src/config

Starting deployment. Account id: francis, node: http://localhost:3030, helper: undefined, file: /Users/zaver/Projects/nearcore/runtime/rust-api/test-contract/pkg/test_contract_bg.wasm
Error:  Error: [1] Error calling abci_query(account/francis,,0,false)
Message: undefined
account francis does not exist while viewing
    at NearClient.jsonRpcRequest (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/nearclient.js:108:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async NearClient.viewAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/nearclient.js:23:26)
    at async NearClient.getNonce (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/nearclient.js:87:17)
    at async Near.deployContract (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/near.js:128:23)
    at async Object.exports.deploy (/usr/local/lib/node_modules/near-shell/index.js:78:9)
    at async exitOnError (/usr/local/lib/node_modules/near-shell/bin/near:8:5) {
  log: 'account francis does not exist while viewing'
```

**Comment by vgrichina** [comment]
Not sure what you talking about. `near deploy` shouldn't require "TypeScript project". There is `--wasmFile` option which allows you to specify path to file to deploy.
You might want to have `src/config.js`, but if you don't have it – should be possible to configure all the same stuff via command line.

May you describe how exactly are you trying to use it / what errors do you get?

**Comment by nearmax** [comment]
Updated the description with instructions on how to reproduce.

**Comment by nearmax** [comment]
Also, does not work with even when I have local contract helper running.
To reproduce:
```
near deploy --useDevAccount --account_id "francis" --wasmFile /Users/zaver/Projects/nearcore/runtime/rust-api/test-contract/pkg/test_contract_bg.wasm --helperUrl http://localhost/contract-api
[WARNING] Didn't find config at /Users/zaver/Projects/near-shell/src/config

Starting deployment. Account id: francis, node: http://localhost:3030, helper: http://localhost/contract-api, file: /Users/zaver/Projects/nearcore/runtime/rust-api/test-contract/pkg/test_contract_bg.wasm
Error:  Error: [1] Error calling abci_query(account/francis,,0,false)
Message: undefined
account francis does not exist while viewing
    at NearClient.jsonRpcRequest (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/nearclient.js:108:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async NearClient.viewAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/nearclient.js:23:26)
    at async NearClient.getNonce (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/nearclient.js:87:17)
    at async Near.deployContract (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/near.js:128:23)
    at async Object.exports.deploy (/usr/local/lib/node_modules/near-shell/index.js:78:9)
    at async exitOnError (/usr/local/lib/node_modules/near-shell/bin/near:8:5) {
  log: 'account francis does not exist while viewing'
```

**Comment by nearmax** [comment]
CC @potatodepaulo 
As discussed we need the following three steps to work for Rust users:
* Create an account;
* Deploy the wasm file as a contract;
* Run a method on the contract.

You can find Rust contract here: https://www.dropbox.com/s/l8vjk0p6aef52as/test_contract_bg.wasm?dl=0

It supports the following methods:
* `add_agent` without args (uses the transaction sender account id to create an agent);
* `simulate` with args: `"{"account_id":"francis.near"}"`, where `francis.near` is account id of whatever account created transaction that called `add_agent`;
* `assets_quantity` with args: `"{"account_id":"francis.near","asset":"MissionTime"}"`
See examples of calling these methods from integration test here:
https://github.com/nearprotocol/nearcore/blob/8f5f0d608a076f175fce5860f34363afc3b3b5d2/runtime/rust-api/tests/test_test_contract.rs#L136

**Comment by vgrichina** [comment]
> Near shell cannot be used for users working with Rust contracts:

> It requires config.js;
> It requires contract helper. near shell is supposed to supersede pynear, by pynear was able to work without locally running contract helper.

I fail to see how either of this disallows Rust developers from using the system. Main point is to support writing smart contracts in Rust, not to avoid any .js in tools (e.g. you'll still use nearlib anyway).

Make sure you have latest near-shell (0.6), following worked fine for me:

```
➜  near-shell git:(master) near create_account --useDevAccount "francis"   
[WARNING] Didn't find config at /Users/vg/Documents/near-shell/src/config

Create account complete for francis
```
```
➜  near-shell git:(master) near deploy --accountId francis --wasmFile ../near-memegen/out/main.wasm
[WARNING] Didn't find config at /Users/vg/Documents/near-shell/src/config

Starting deployment. Account id: francis, node: http://localhost:3030, helper: undefined, file: ../near-memegen/out/main.wasm
Deployment succeeded.
```

No `--useDevAccount` for deploy, cause it has to use `francis` account.

**Comment by potatodepaulo** [comment]
I think it's fine that it works here, but I think it should be easier than knowing you need to use these specific flags. Creating accounts is confusing as it stands today.

**Comment by vgrichina** [comment]
@potatodepaulo agree it is confusing, medium-term plan is to abolish `--useDevAccount` altogether and instead have `near-shell` look for local `nearcore` config (cause it'll need to read super account keys from there).

However issue description sounds like it's blocking Rust API development, which I think isn't a case here.

**Comment by nearmax** [comment]
@vgrichina Thanks for the correct commands, it seems to be working now. It is not an urgent blocker anymore.

**Comment by ilblackdragon** [comment]
I'm going to change as part of Nightshade upgrade to make it work by looking at local config for keys.

Currently configs in ~/.near are in Json format, so I'm assuming same should work for project specific configs as well (instead of config.js)

**Comment by vgrichina** [comment]
@ilblackdragon  config.js is providing support for multiple NODE_ENVs and Studio fiddles, make sure this still is the case after changes.
