### ISSUE TITLE
../near-shell/bin/near create_account --accountId jane123 doesn't work

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-shell#55]
Not enough non-option arguments: got 0, need at least 1
This syntax is supposed to work

**Comment by potatodepaulo** [comment]
We've changed to positional arguments. What is the use case where this would be preferable to
```
near create_account jane123
```

**Comment by janedegtiareva** [comment]
That might be fine, but help message was not updated, so it's very confusing if you are trying to figure out syntax from help. 
We need to remove account id option from the list for create_account. 

this is what help for create_account outputs right now


near create_account <accountId>

create a developer account

Options:
  --help                     Show help                                 [boolean]
  --version                  Show version number                       [boolean]
  --nodeUrl, --node_url      NEAR node URL
                                     [string] [default: "http://localhost:3030"]
  --networkId, --network_id  NEAR network ID, allows using different keys based
                             on network            [string] [default: "default"]
  --helperUrl                NEAR contract helper URL                   [string]
  --keyPath                  Path to master account key                 [string]
  --homeDir                  Where to look for master account, default is
                             ~/.near
                           [string] [default: "/Users/evgueniadegtiareva/.near"]
  --useDevAccount            Forces use of special "developer" account (only
                             works on local node)                      [boolean]
  --accountId, --account_id  Unique identifier for the newly created account
                                                             [string] [required]

**Comment by potatodepaulo** [comment]
Okay, will fix messaging.
