### ISSUE TITLE
Allow to create account with specified public key

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#60]
`near create_account illia.near PUB_KEY <amount>`

**Comment by janedegtiareva** [comment]
Why do we need this? We already have an ability to specify an account id.

**Comment by vgrichina** [comment]
for setups where you don't want to have private key on device where you create account (for security reasons)

**Comment by vgrichina** [comment]
@ilblackdragon I think that key and amount should be optional though, so you'd do:
```
near create_account illia.near --publicKey encoded_key --amount 1000000
```

**Comment by janedegtiareva** [comment]
https://github.com/nearprotocol/near-shell/pull/78

**Comment by janedegtiareva** [comment]
fixed with previously quoted PR
