### ISSUE TITLE
Unsupported Platform in fsevents Dependency

### ISSUE THREAD

**Issue by joesixpack** [nearprotocol/near-shell#64]
Can't install near-shell via npm due to:

![image](https://user-images.githubusercontent.com/23145642/61330475-85ba5f80-a7d4-11e9-886a-dc0f192bff45.png)

**Comment by janedegtiareva** [comment]
Hello,
We've recently updated a lot of dependencies in near-shell, so this issue might not be happening anymore. Could you try again with near-shell@0.9.1? Thank you!

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/62633417-f262de80-b8e8-11e9-852b-12e04051e7bc.png)
