### ISSUE TITLE
Upgrade to gulp 4 (gulp 3 is not supported and does not work with latest node)

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-shell#84]

**Comment by janedegtiareva** [comment]
https://github.com/nearprotocol/near-shell/pull/85/files

**Comment by janedegtiareva** [comment]
issue fixed

**Comment by vgrichina** [comment]
What about corresponding changes in studio?

**Comment by janedegtiareva** [comment]
I filed separate issues so that we can close them independently. https://github.com/nearprotocol/NEARStudio/issues/137
