### ISSUE TITLE
'near send' is broken

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/near-shell#91]
What should happen:
```bash
near send loaded.potato 1000000000
# All good. You sent a bunch o money
```
What's happening:
<img width="1232" alt="Screenshot 2019-08-01 12 24 38" src="https://user-images.githubusercontent.com/6679554/62326997-4e9aae00-b464-11e9-87af-2d8a4d2562d6.png">

**Comment by janedegtiareva** [comment]
I think we need an explicit param for the account you are sending from 
../near-shell/bin/near send janesend1 10 --accountId janesend2 ?

**Comment by potatodepaulo** [comment]
I wanted to add from conversation: We should add a param for <sender>
E.g. 
```bash
near send <recipient> <sender> <pubKey> <amount>

near send loaded.potato tasty.potato FQrWi8AQhmfe9dxq2C1DimPuDBmU2v6WoyqgmyQ9FS5g 999999999
```

I'm not sure which should come first if we rely on positional args. I could be convinced that recipient is a flag, but that would be adding yet another option to a growing list.

**Comment by potatodepaulo** [comment]
> I think we need an explicit param for the account you are sending from
> ../near-shell/bin/near send janesend1 10 --accountId janesend2 ?

I was going to push back about this, but as long as we document this clearly, I like it.
Behavior:
Default: sends from `masterAccount`
With accountId: sends from specified accountId.

Pretty simple.

**Comment by janedegtiareva** [comment]
positional are fine too. 
Why do we need pub key though?

**Comment by janedegtiareva** [comment]
I've actually convinced myself that positional arguments that are always required are better. Sending money is not a reversible operation, so having a weird hidden default could be bad. It's much better to have one single way the command works.

**Comment by potatodepaulo** [comment]
> I've actually convinced myself that positional arguments that are always required are better. Sending money is not a reversible operation, so having a weird hidden default could be bad. It's much better to have one single way the command works.

That works for me. 

> positional are fine too.
> Why do we need pub key though?
oops! Edited.

**Comment by janedegtiareva** [comment]
The order of positionals is not that critical. There are basically 2 cases:
a) they have private keys for both accounts. Then if they accidentally swap the 2 accounts, they could undo the mistake by using the other private key
b) they have only one private key for sender. The operation will straight out fail since sender key is not available.

**Comment by janedegtiareva** [comment]
https://github.com/nearprotocol/near-shell/pull/92
